### ISSUE TITLE
coco.yaml file

### ISSUE THREAD

**Issue by gedw99** [SAP/configuration-tools-for-gitops#31]
this looks really useful.

is there an example cooc.yaml file to get started learning this ?

**Comment by blackhatcrazy** [comment]
Hi gedw99, 

first of all thank you for reaching out!

At the moment unfortunately our UX documentation is still lacking behind and we don't have a nice end-to-end example readily consumable.

I assume, you're referring to the component configuration file and not to the CLI configuration, right?

In that case, component configurations are very limited at the moment.
You can only specify the component's name and the direct dependencies that the component consumes, e.g.

```yaml
name: my-component
dependencies:
- first-dependency-that-I-consume
- second-dependency-that-I-consume
- ...
```

Currently, the file is only used for dependency graph generation and evaluation.
